"""Base team metadata used to construct teams.json output."""

TEAM_METADATA = [
    {
        "team_abbr": "ARI",
        "city": "Arizona",
        "mascot": "Cardinals",
        "division": "NFC West",
        "conference": "NFC",
        "espn_api_id": 22,
        "primary_color": "#97233F",
        "secondary_color": "#000000",
    },
    {
        "team_abbr": "ATL",
        "city": "Atlanta",
        "mascot": "Falcons",
        "division": "NFC South",
        "conference": "NFC",
        "espn_api_id": 1,
        "primary_color": "#A71930",
        "secondary_color": "#000000",
    },
    {
        "team_abbr": "BAL",
        "city": "Baltimore",
        "mascot": "Ravens",
        "division": "AFC North",
        "conference": "AFC",
        "espn_api_id": 33,
        "primary_color": "#241773",
        "secondary_color": "#000000",
    },
    {
        "team_abbr": "BUF",
        "city": "Buffalo",
        "mascot": "Bills",
        "division": "AFC East",
        "conference": "AFC",
        "espn_api_id": 2,
        "primary_color": "#00338D",
        "secondary_color": "#C60C30",
    },
    {
        "team_abbr": "CAR",
        "city": "Carolina",
        "mascot": "Panthers",
        "division": "NFC South",
        "conference": "NFC",
        "espn_api_id": 29,
        "primary_color": "#0085CA",
        "secondary_color": "#101820",
    },
    {
        "team_abbr": "CHI",
        "city": "Chicago",
        "mascot": "Bears",
        "division": "NFC North",
        "conference": "NFC",
        "espn_api_id": 3,
        "primary_color": "#0B162A",
        "secondary_color": "#C83803",
    },
    {
        "team_abbr": "CIN",
        "city": "Cincinnati",
        "mascot": "Bengals",
        "division": "AFC North",
        "conference": "AFC",
        "espn_api_id": 4,
        "primary_color": "#FB4F14",
        "secondary_color": "#000000",
    },
    {
        "team_abbr": "CLE",
        "city": "Cleveland",
        "mascot": "Browns",
        "division": "AFC North",
        "conference": "AFC",
        "espn_api_id": 5,
        "primary_color": "#311D00",
        "secondary_color": "#FF3C00",
    },
    {
        "team_abbr": "DAL",
        "city": "Dallas",
        "mascot": "Cowboys",
        "division": "NFC East",
        "conference": "NFC",
        "espn_api_id": 6,
        "primary_color": "#003594",
        "secondary_color": "#041E42",
    },
    {
        "team_abbr": "DEN",
        "city": "Denver",
        "mascot": "Broncos",
        "division": "AFC West",
        "conference": "AFC",
        "espn_api_id": 7,
        "primary_color": "#FB4F14",
        "secondary_color": "#002244",
    },
    {
        "team_abbr": "DET",
        "city": "Detroit",
        "mascot": "Lions",
        "division": "NFC North",
        "conference": "NFC",
        "espn_api_id": 8,
        "primary_color": "#0076B6",
        "secondary_color": "#B0B7BC",
    },
    {
        "team_abbr": "GB",
        "city": "Green Bay",
        "mascot": "Packers",
        "division": "NFC North",
        "conference": "NFC",
        "espn_api_id": 9,
        "primary_color": "#203731",
        "secondary_color": "#FFB612",
    },
    {
        "team_abbr": "HOU",
        "city": "Houston",
        "mascot": "Texans",
        "division": "AFC South",
        "conference": "AFC",
        "espn_api_id": 34,
        "primary_color": "#03202F",
        "secondary_color": "#A71930",
    },
    {
        "team_abbr": "IND",
        "city": "Indianapolis",
        "mascot": "Colts",
        "division": "AFC South",
        "conference": "AFC",
        "espn_api_id": 11,
        "primary_color": "#002C5F",
        "secondary_color": "#A2AAAD",
    },
    {
        "team_abbr": "JAX",
        "city": "Jacksonville",
        "mascot": "Jaguars",
        "division": "AFC South",
        "conference": "AFC",
        "espn_api_id": 30,
        "primary_color": "#006778",
        "secondary_color": "#9F792C",
    },
    {
        "team_abbr": "KC",
        "city": "Kansas City",
        "mascot": "Chiefs",
        "division": "AFC West",
        "conference": "AFC",
        "espn_api_id": 12,
        "primary_color": "#E31837",
        "secondary_color": "#FFB81C",
    },
    {
        "team_abbr": "LAC",
        "city": "Los Angeles",
        "mascot": "Chargers",
        "division": "AFC West",
        "conference": "AFC",
        "espn_api_id": 24,
        "primary_color": "#0080C6",
        "secondary_color": "#FFC20E",
    },
    {
        "team_abbr": "LAR",
        "city": "Los Angeles",
        "mascot": "Rams",
        "division": "NFC West",
        "conference": "NFC",
        "espn_api_id": 14,
        "primary_color": "#003594",
        "secondary_color": "#FFA300",
    },
    {
        "team_abbr": "LV",
        "city": "Las Vegas",
        "mascot": "Raiders",
        "division": "AFC West",
        "conference": "AFC",
        "espn_api_id": 13,
        "primary_color": "#000000",
        "secondary_color": "#A5ACAF",
    },
    {
        "team_abbr": "MIA",
        "city": "Miami",
        "mascot": "Dolphins",
        "division": "AFC East",
        "conference": "AFC",
        "espn_api_id": 15,
        "primary_color": "#008E97",
        "secondary_color": "#FC4C02",
    },
    {
        "team_abbr": "MIN",
        "city": "Minnesota",
        "mascot": "Vikings",
        "division": "NFC North",
        "conference": "NFC",
        "espn_api_id": 16,
        "primary_color": "#4F2683",
        "secondary_color": "#FFC62F",
    },
    {
        "team_abbr": "NE",
        "city": "New England",
        "mascot": "Patriots",
        "division": "AFC East",
        "conference": "AFC",
        "espn_api_id": 17,
        "primary_color": "#002244",
        "secondary_color": "#C60C30",
    },
    {
        "team_abbr": "NO",
        "city": "New Orleans",
        "mascot": "Saints",
        "division": "NFC South",
        "conference": "NFC",
        "espn_api_id": 18,
        "primary_color": "#D3BC8D",
        "secondary_color": "#101820",
    },
    {
        "team_abbr": "NYG",
        "city": "New York",
        "mascot": "Giants",
        "division": "NFC East",
        "conference": "NFC",
        "espn_api_id": 19,
        "primary_color": "#0B2265",
        "secondary_color": "#A71930",
    },
    {
        "team_abbr": "NYJ",
        "city": "New York",
        "mascot": "Jets",
        "division": "AFC East",
        "conference": "AFC",
        "espn_api_id": 20,
        "primary_color": "#125740",
        "secondary_color": "#000000",
    },
    {
        "team_abbr": "PHI",
        "city": "Philadelphia",
        "mascot": "Eagles",
        "division": "NFC East",
        "conference": "NFC",
        "espn_api_id": 21,
        "primary_color": "#004C54",
        "secondary_color": "#A5ACAF",
    },
    {
        "team_abbr": "PIT",
        "city": "Pittsburgh",
        "mascot": "Steelers",
        "division": "AFC North",
        "conference": "AFC",
        "espn_api_id": 23,
        "primary_color": "#FFB612",
        "secondary_color": "#101820",
    },
    {
        "team_abbr": "SF",
        "city": "San Francisco",
        "mascot": "49ers",
        "division": "NFC West",
        "conference": "NFC",
        "espn_api_id": 25,
        "primary_color": "#AA0000",
        "secondary_color": "#B3995D",
    },
    {
        "team_abbr": "SEA",
        "city": "Seattle",
        "mascot": "Seahawks",
        "division": "NFC West",
        "conference": "NFC",
        "espn_api_id": 26,
        "primary_color": "#002244",
        "secondary_color": "#69BE28",
    },
    {
        "team_abbr": "TB",
        "city": "Tampa Bay",
        "mascot": "Buccaneers",
        "division": "NFC South",
        "conference": "NFC",
        "espn_api_id": 27,
        "primary_color": "#D50A0A",
        "secondary_color": "#34302B",
    },
    {
        "team_abbr": "TEN",
        "city": "Tennessee",
        "mascot": "Titans",
        "division": "AFC South",
        "conference": "AFC",
        "espn_api_id": 10,
        "primary_color": "#0C2340",
        "secondary_color": "#4B92DB",
    },
    {
        "team_abbr": "WAS",
        "city": "Washington",
        "mascot": "Commanders",
        "division": "NFC East",
        "conference": "NFC",
        "espn_api_id": 28,
        "primary_color": "#773141",
        "secondary_color": "#FFB612",
    },
]

