name: Slate Refresh

on:
  workflow_dispatch:
    inputs:
      preset:
        description: Preset to run via generate_cache_cli
        required: true
        type: choice
        options:
          - full-production-50k
          - full-production-100k
          - full-dev-50k-copy-local-no-deploy
          - regenerate-detroit-no-deploy
          - quick-test-sims-no-ai
          - regenerate-all-ai-no-sims-deploy
          - gen-ai-haiku-no-sims-no-deploy
          - gen-ai-opus-no-sims-no-deploy
          - regenerate-dashboard-only-no-deploy
          - regenerate-dashboard-only-and-deploy
          - refresh-ai-weekly-no-sims-deploy
        default: full-production-50k
      sleep_seconds:
        description: Polling interval in seconds (default 60)
        required: false
        default: "60"
      lead_minutes:
        description: Include games starting within this many minutes
        required: false
        default: "0"
      max_wait:
        description: Max minutes to wait before exiting (0 = unlimited within job timeout)
        required: false
        default: "0"
      force_run:
        description: "Set to true to bypass slate detection and run immediately"
        required: false
        default: "false"

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run slate watcher
        run: |
          FORCE_FLAG=""
          if [ "${{ github.event.inputs.force_run }}" = "true" ]; then
            FORCE_FLAG="--force-run"
          fi
          python scripts/slate_watcher.py \
            --preset "${{ github.event.inputs.preset }}" \
            --sleep "${{ github.event.inputs.sleep_seconds }}" \
            --lead-minutes "${{ github.event.inputs.lead_minutes }}" \
            --max-wait "${{ github.event.inputs.max_wait }}" \
            $FORCE_FLAG
